stages:
  - buildarm64v8

build:
  tags:
    - docker
  stage: buildarm64v8
  script:
    - docker buildx build --tag w3bstream:arm64v8 --platform linux/arm64 -f Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 --progress=plain --file Dockerfile --ssh default .
