stages:
  # - build
  # - publish
  - run

# build:
#   tags:
#     - docker
#   stage: build
#   script:
#     - make images

# publish:
#   tags:
#     - docker
#   stage: publish
#   script:
#     - docker login -u $DockerUsername -p $DockerPassword
#     - make push_docker

run:
  tags:
    - w3bstream
  stage: run
  script:
    - make run_docker
